// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Week04/controller"
	"Week04/service"
	"context"
	"net/http"
)

// Injectors from wire.go:

func InitHttpHandler(msg string, ctx context.Context) http.Handler {
	userService := service.UserServiceFun(msg)
	handler := controller.HttpHandler(ctx, userService)
	return handler
}
